apiVersion: v1
kind: Service
metadata:
  name: email-sender-service
spec:
  selector:
    app: email-sender-service
  type: ClusterIP
  ports:
    - name: http
      port: 8081
      targetPort: 8081
