apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base

# Image versions - updated by CI/CD
images:
- name: email-sender-service
  newName: ghcr.io/halmber/email-sender-service
  newTag: latest
- name: frontend-service
  newName: ghcr.io/halmber/orders-frontend
  newTag: 58c727e5b3412bd464d69f292466bbdbead45989
- name: gateway-service
  newName: ghcr.io/halmber/orders-api-gateway
  newTag: latest
- name: orders-api-service
  newName: ghcr.io/halmber/orders-api-service
  newTag: latest
